name: C++ Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cài đặt g++
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Biên dịch
        run: g++ -std=c++17 -O2 -o test_classify test_classify.cpp

      - name: Chạy test
        run: ./test_classify
